### ISSUE TITLE
Alarm state Home/Away/Disarmed

### ISSUE THREAD

**Issue by SgtHobNob** [jasonmadigan/ha-hkc#11]
Is it possible to add an additional armed state?

My alarm is configured for Full Arm, Part Arm A (Night Arm), Part Arm B (Garage only)

Currently Part Arm A Is Armed Home and Part Arm B displays as Disarmed. Ideally I'd like to read/set each state.

Thank you for your hard word on this integration.

**Comment by jasonmadigan** [comment]
thanks for raising @SgtHobNob - I'll take a look into some options here. 

We'd have to pick an existing state from HA's alarm component that would work to map another part-set arming type to - something from this list:
https://developers.home-assistant.io/docs/core/entity/alarm-control-panel/#states

**Comment by SgtHobNob** [comment]
I’d really appreciate it, for me the armed_home status would work great for part set B, the only problem is for others it could be the other way around! Thanks

**Comment by jasonmadigan** [comment]
Partset B added recently:

https://github.com/jasonmadigan/ha-hkc/releases/tag/1.0.17
https://github.com/jasonmadigan/ha-hkc/blob/main/README.md#entities

**Comment by jmccrohan** [comment]
@jasonmadigan Must the Part Set A/B -> Arm Home/Arm Night mappings be hardcoded, or could they potentially be defined/disabled as part of config_flow?

On my HKC alarm, I have Part Set A configured as Night Set, and Part Set B configured as basically Full Set (with PIRs disabled). Prior to #24 being merged, the HA mapping was Armed Away and Armed Home, which made sort of sense for Full Set and Night Mode, but since Armed Night was added, this mapping makes little sense.

**Comment by jasonmadigan** [comment]
@jmccrohan Sorry, this got buried in a bunch of notifications during the hols. I think the easiest way to solve this for you and others who want to customise mappings, might be to create a template alarm_panel. Something like:

```yaml
# Where "alarm_control_panel.real_alarm" is the HKC alarm created by the integration
alarm_control_panel:
  - platform: template
    panels:
      my_panel:
        value_template: "{{ states('alarm_control_panel.real_alarm') }}"
        arm_away:
          action: alarm_control_panel.alarm_arm_away
          target:
            entity_id: alarm_control_panel.real_alarm
          data:
            code: !secret alarm_code
        arm_home:
          action: alarm_control_panel.alarm_arm_night  # Using Part Set B as Home mode
          target:
            entity_id: alarm_control_panel.real_alarm
          data:
            code: !secret alarm_code
        arm_night:
          action: alarm_control_panel.alarm_arm_home   # Using Part Set A as Night mode
          target:
            entity_id: alarm_control_panel.real_alarm
          data:
            code: !secret alarm_code
        disarm:
          - action: alarm_control_panel.alarm_disarm
            target:
              entity_id: alarm_control_panel.real_alarm
            data:
              code: !secret alarm_code
```
